// Generated by CoffeeScript 1.10.0
(function() {
  var Response;

  Response = (function() {
    function Response(state, message, data) {
      this.state = state;
      this.message = message;
      this.data = data != null ? data : null;
    }

    return Response;

  })();

  exports.Response = Response;

}).call(this);
