// Generated by CoffeeScript 1.6.1
(function() {

  exports.db = {
    host: "127.0.0.1",
    port: 6379,
    db: 0,
    pass: null
  };

  exports.sessiondb = {
    host: "127.0.0.1",
    port: 6379,
    db: 1,
    pass: null
  };

}).call(this);
