// Generated by CoffeeScript 1.10.0
(function() {
  exports.db = {
    host: "127.0.0.1",
    port: 6379,
    db: 0,
    pass: null
  };

  exports.sessiondb = {
    host: "127.0.0.1",
    port: 6379,
    db: 1,
    pass: null
  };

  exports.app = {
    port: 3000
  };

  exports.mysql = {
    host: "127.0.0.1",
    port: 3306,
    db: "wordpress",
    username: "root",
    pass: "root"
  };

}).call(this);
