// Generated by CoffeeScript 1.6.1
(function() {

  exports.index = function(req, res) {
    return res.render("admin/department");
  };

  exports.usersIndex = function(req, res) {
    return res.render("admin/users");
  };

}).call(this);
