// Generated by CoffeeScript 1.10.0
(function() {
  var utils;
  utils = require('../utils');
  blogModel = require('../models/blogModel');
  exports.index = function(req, res) {
    var conn, data;
    data = {
      blogname: "书摘"
    };
    return res.render("blog/index", data);
  };

  exports.getblogs = function(req, res) {
    return blogModel.getBlogs(function(response) {
        return res.send(response);
      });
  };
  
  exports.addBlog = function(req,res) {
  	var postContent;
  	postContent = req.body.post_content;
  	try {
  		return blogModel.addBlogs(postContent, function(response) {
        return res.send(response);
      });
  	} catch (error1) {
      error = error1;
      return res.send(new Response(0, "error"));
    }
  	//console.log(req);
  };

}).call(this);
