// Generated by CoffeeScript 1.6.1
(function() {
  var Response, check, crypto, departmentModel, sanitize, userModel;

  crypto = require('crypto');

  check = require('validator').check;

  sanitize = require('validator').sanitize;

  userModel = require('../models/usersModel');

  departmentModel = require('../models/departmentsModel');

  Response = require('../vo/Response').Response;

  exports.index = function(req, res) {
    return res.render("admin/department");
  };

  exports.usersIndex = function(req, res) {
    return res.render("admin/users");
  };

  exports.createDepartment = function(req, res) {
    var departmentName, errorMessage, parentId;
    departmentName = sanitize(req.body.departmentName).trim();
    parentId = sanitize(req.body.pid).trim();
    errorMessage = "";
    try {
      check(departmentName, "部门名称不能为空").notEmpty().notContains(":");
      return departmentModel.createDepartment(departmentName, parentId, function(response) {
        return res.send(response);
      });
    } catch (error) {
      errorMessage = error.message;
      return res.send(new Response(0, errorMessage));
    }
  };

  exports.removeDepartment = function(req, res) {
    var departmentId;
    departmentId = sanitize(req.body.departmentId).trim();
    return departmentModel.removeDepartment(departmentId, function(response) {
      return res.send(response);
    });
  };

  exports.updateDepartment = function(req, res) {
    var departmentId, departmentName, errorMessage, parentId;
    departmentId = sanitize(req.body.departmentId).trim();
    departmentName = sanitize(req.body.departmentName).trim();
    parentId = sanitize(req.body.pid).trim();
    try {
      check(departmentName, "部门名称不能为空").notEmpty().notContains(":");
      return departmentModel.updateDepartment(departmentId, departmentName, parentId, function(response) {
        return res.send(response);
      });
    } catch (error) {
      errorMessage = error.message;
      return res.send(new Response(0, errorMessage));
    }
  };

  exports.getAllDepartments = function(req, res) {
    return departmentModel.getAllDepartments(function(response) {
      return res.send(response);
    });
  };

}).call(this);
