// Generated by CoffeeScript 1.6.1
(function() {

  exports.index = function(req, res) {
    return res.render("index");
  };

  exports.write = function(req, res) {
    return res.render("write");
  };

}).call(this);
