// Generated by CoffeeScript 1.6.1
(function() {
  var Response, check, crypto, reportModel, sanitize, showPage, userModel;

  crypto = require('crypto');

  check = require('validator').check;

  sanitize = require('validator').sanitize;

  reportModel = require('../models/reportModel');

  userModel = require('../models/usersModel');

  Response = require('../vo/Response').Response;

  exports.writeIndex = function(req, res) {
    var userId;
    userId = "28";
    return showPage(res, userId, "write");
  };

  exports.write = function(req, res) {
    var content, date, dateStr, errorMessage, months, year, _ref;
    dateStr = sanitize(req.body.date).trim();
    content = sanitize(req.body.content).trim();
    errorMessage = "";
    try {
      check(dateStr).notEmpty();
      check(content).notEmpty();
      _ref = dateStr.split("-"), year = _ref[0], months = _ref[1], date = _ref[2];
      check(year).notNull().isNumeric().len(4, 4);
      check(months).notNull().isNumeric().len(1, 2);
      check(date).notNull().isNumeric().len(1, 2);
      return reportModel.createReport("28", content, dateStr, function(response) {
        return res.send(response);
      });
    } catch (error) {
      return res.send(new Response(0, "日期格式不正确或者内容为空"));
    }
  };

  exports.showIndex = function(req, res) {
    var userId;
    userId = "28";
    return showPage(res, userId, "show");
  };

  showPage = function(res, userId, pageTitle) {
    return userModel.hasSubordinate(userId, function(result) {
      var data;
      data = {
        hasSubordinate: result
      };
      return res.render(pageTitle, data);
    });
  };

  exports.showsubordinateIndex = function(req, res) {
    return userModel.hasSubordinate("28", function(result) {
      if (result) {
        return res.render("showsubordinate");
      } else {
        return res.send("您目前没有下属");
      }
    });
  };

  exports.getReports = function(req, res) {
    var errorMessage, numOfPage, page, userId;
    page = sanitize(req.body.page).trim();
    userId = sanitize(req.body.userId).trim();
    console.log("userId:" + userId);
    if (userId == null) {
      userId = "28";
    }
    console.log("userId:" + userId);
    numOfPage = sanitize(req.body.numOfPage).trim();
    errorMessage = "";
    try {
      check(page).isNumeric().min(1);
      check(page).isNumeric().min(1);
      return reportModel.getReports(userId, page, numOfPage, function(response) {
        return res.send(response);
      });
    } catch (error) {
      return res.send(new Response(0, "页数和每页显示条数为非负数"));
    }
  };

  exports.getReportNum = function(req, res) {
    var userId;
    userId = sanitize(req.body.userId).trim();
    if (userId == null) {
      userId = "28";
    }
    return reportModel.getReportNum(userId, function(response) {
      return res.send(response);
    });
  };

  exports["delete"] = function(req, res) {
    var reportId;
    reportId = req.body.reportId;
    return reportModel.deleteReport("28", reportId, function(response) {
      return res.send(response);
    });
  };

  exports.getSubordinateUserAndDepartment = function(req, res) {
    var userId;
    userId = "28";
    return reportModel.getSubordinateUserAndDepartment("28", function(response) {
      return res.send(response);
    });
  };

}).call(this);
