// Generated by CoffeeScript 1.6.1
(function() {

  exports.loginIndex = function(req, res) {
    return res.render("login");
  };

  exports.login = function(req, res) {
    var password, username;
    username = req.body.userName;
    password = req.body.password;
    return res.redirect('/admin');
  };

  exports.createUser = function(req, res) {
    var errorMessage, hashedPassword, password, userName;
    userName = sanitize(req.body.userName).trim();
    password = sanitize(req.body.password).trim();
    errorMessage = "";
    try {
      check(userName, "字符长度为6-25，不能含有:符号").len(6, 25).notContains(":");
    } catch (error) {
      errorMessage = error.message;
    }
    try {
      check(password, "字符长度为7-25，不能含有:符号").len(7, 25).notContains(":");
    } catch (error) {
      errorMessage = "" + errorMessage + ", " + error.message;
    }
    if (errorMessage === "") {
      hashedPassword = crypto.createHash("sha1").update(password).digest('hex');
      return userModel.createUser(userName, hashedPassword, function(response) {
        return res.send(response);
      });
    } else {
      return res.send(new Response(0, errorMessage));
    }
  };

}).call(this);
