// Generated by CoffeeScript 1.6.1
(function() {
  var departmentModel, userModel;

  userModel = require('../models/usersModel');

  departmentModel = require('../models/departmentsModel');

  exports.index = function(req, res) {
    return res.render("admin/department");
  };

  exports.usersIndex = function(req, res) {
    return res.render("admin/users");
  };

  exports.createUser = function(req, res) {
    var password, userName;
    userName = req.body.userName;
    password = req.body.password;
    return userModel.createUser(userName, password, function(response) {
      return res.send(response);
    });
  };

  exports.createDepartment = function(req, res) {
    var departmentName, parentId;
    departmentName = req.body.departmentName;
    parentId = req.body.pid;
    return departmentModel.createDepartment(departmentName, parentId, function(response) {
      return res.send(response);
    });
  };

  exports.getAllDepartments = function(req, res) {
    return departmentModel.getAllDepartments(function(response) {
      return res.send(response);
    });
  };

}).call(this);
