// Generated by CoffeeScript 1.6.1
(function() {
  var userModel;

  userModel = require('../models/usersModel');

  exports.index = function(req, res) {
    return res.render("admin/department");
  };

  exports.usersIndex = function(req, res) {
    return res.render("admin/users");
  };

  exports.createUser = function(req, res) {
    var password, userName;
    userName = req.body.userName;
    password = req.body.password;
    return userModel.createUser(userName, password, function(response) {
      return res.send(response);
    });
  };

}).call(this);
