// Generated by CoffeeScript 1.6.1
(function() {
  var redis;

  redis = require("redis");

  exports.index = function(req, res) {
    return res.render("admin/department");
  };

  exports.usersIndex = function(req, res) {
    return res.render("admin/users");
  };

  exports.createUser = function(req, res) {
    var client, password, userName;
    userName = req.body.userName;
    password = req.body.password;
    client = redis.createClient();
    client.incr("next_user_id", function(err, reply) {
      client.hset("users", "" + reply + ":user_name", userName);
      client.hset("users", "" + reply + ":password", password);
      client.hset("users", "" + userName + ":user_id", reply);
      return client.quit();
    });
    return res.send(1);
  };

}).call(this);
