// Generated by CoffeeScript 1.6.1
(function() {
  var admin, user;

  user = require('../controlers/userCtr');

  admin = require('../controlers/adminCtr');

  exports.createRutes = function(app) {
    app.get('/login', user.loginIndex);
    app.post('/login', user.login);
    app.get('/admin', admin.index);
    app.post('/admin/createdepartment', admin.createDepartment);
    app.get('/admin/users', admin.usersIndex);
    app.post('/admin/createusers', admin.createUser);
    app.get('/admin/alldepartments', admin.getAllDepartments);
    app.post('/admin/removedepartment', admin.removeDepartment);
    return app.post('/admin/updatedepartment', admin.updateDepartment);
  };

}).call(this);
