// Generated by CoffeeScript 2.0.0-beta4
exports.loginIndex = function (req, res) {
  return res.render('login');
};
exports.login = function (req, res) {
  var password, username;
  username = req.body.userName;
  password = req.body.password;
  return res.redirect('/admin');
};
