// Generated by CoffeeScript 1.10.0
(function() {
	var Response, getDateNumber, getDepartTreeData, parseDepartments, parseUsers, userModel, utils;

	Response = require('../vo/Response').Response;

	userModel = require('./usersModel');

	utils = require("../utils");

	exports.getBlogs = function(callback) {
		conn = utils.createMysql();
		conn.query('SELECT * from  wp_posts', function(err, rows, fields) {
			response = [];
			len = rows.length;
			for (i = 0; i < len; i++) {
				response.push(
					rows[i]
				);
			}
			conn.end();
			return callback(new Response(1, 'success', response));
		});
	};

	exports.addBlogs = function(post_content, callback) {
		conn = utils.createMysql();
		var addSql = 'INSERT INTO wp_posts (post_content) VALUES(?)';
		var addParams = [post_content];
		conn.query(addSql, addParams, function(err, result) {
			response = [];
			if (err) {
				console.log('[INSERT ERROR] - ', err.message);
				return callback(new Response(0, 'error', response));
			} else {
				return callback(new Response(1, 'success', response));
			}
		});
		console.log(post_content)
	}
}).call(this);