// Generated by CoffeeScript 1.6.1
(function() {
  var Response, redis;

  redis = require("redis");

  Response = require('../vo/response').Response;

  exports.createDepartment = function(departmentName, parentId, callback) {
    var client;
    client = redis.createClient();
    return client.incr("next_department_id", function(err, reply) {
      var department, result;
      client.hset("departments", "" + reply + ":name", departmentName);
      result = {
        name: departmentName
      };
      department = {
        name: departmentName,
        id: "" + reply
      };
      if (parentId) {
        client.hset("departments", "" + reply + ":pid", parentId);
        result["pid"] = parentId;
        department["pid"] = parentId;
      }
      client.quit();
      if (callback) {
        return callback(new Response(1, 'success', department));
      }
    });
  };

  exports.removeDepartment = function(departmentId, callback) {
    var client;
    client = redis.createClient();
    return client.hdel("departments", "" + departmentId + ":name", "" + departmentId + ":pid", function(err, reply) {
      client.hgetall("departments", function(err, reply) {
        var childOfKey, key, newDepartments, value;
        newDepartments = {};
        for (key in reply) {
          value = reply[key];
          childOfKey = key.split(":");
          if (childOfKey[1] === "pid" && value === departmentId) {
            client.hdel("departments", key);
          } else {
            newDepartments[key] = value;
          }
        }
        return callback(new Response(1, 'success', newDepartments));
      });
      return client.hgetall("users", function(err, reply) {
        var childOfKey, key, users, value, _i, _len, _results;
        users = reply;
        _results = [];
        for (value = _i = 0, _len = users.length; _i < _len; value = ++_i) {
          key = users[value];
          childOfKey = key.split(":");
          if (childOfKey[1] === "department_id" && value === departmentId) {
            _results.push(client.hdel("users", key));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      });
    });
  };

  exports.updateDepartment = function(departmentId, departmentName, parentId, callback) {
    var client, replycallback;
    client = redis.createClient();
    replycallback = function(err, reply) {
      return client.hgetall("departments", function(err, reply) {
        client.quit();
        return callback(new Response(1, 'success', reply));
      });
    };
    if (parentId) {
      return client.hmset("departments", "" + departmentId + ":name", departmentName, "" + departmentId + ":pid", parentId, replycallback);
    } else {
      return client.hset("departments", "" + departmentId + ":name", departmentName, replycallback);
    }
  };

  exports.getAllDepartments = function(callback) {
    var client;
    client = redis.createClient();
    return client.hgetall("departments", function(err, reply) {
      client.quit();
      if (callback) {
        return callback(new Response(1, 'success', reply));
      }
    });
  };

}).call(this);
