// Generated by CoffeeScript 1.6.1
(function() {
  var redis;

  redis = require("redis");

  exports.createUser = function(userName, password, callback) {
    var client;
    client = redis.createClient();
    return client.incr("next_user_id", function(err, reply) {
      var response;
      client.hset("users", "" + reply + ":user_name", userName);
      client.hset("users", "" + reply + ":password", password);
      client.hset("users", "" + userName + ":user_id", reply);
      client.quit();
      response = {
        state: 1,
        message: 'success'
      };
      if (callback) {
        return callback(response);
      }
    });
  };

}).call(this);
