// Generated by CoffeeScript 1.6.1
(function() {
  var Response, redis;

  redis = require("redis");

  Response = require('../vo/response').Response;

  exports.createUser = function(userName, password, departmentId, superiorId, callback) {
    var client;
    client = redis.createClient();
    return client.incr("next_user_id", function(err, reply) {
      var replycallback, userId;
      userId = reply;
      replycallback = function(err, reply) {
        var data;
        client.quit();
        if (superiorId) {
          data = {
            id: userId,
            userName: userName,
            departmentId: departmentId,
            superiorId: superiorId
          };
        } else {
          data = {
            id: userId,
            userName: userName,
            departmentId: departmentId
          };
        }
        return callback(new Response(1, 'success', data));
      };
      if (superiorId) {
        return client.hmset("users", "" + reply + ":user_name", userName, "" + reply + ":password", password, "" + reply + ":department_id", departmentId, "" + reply + ":superior_id", superiorId, replycallback);
      } else {
        return client.hmset("users", "" + reply + ":user_name", userName, "" + reply + ":password", password, "" + reply + ":department_id", departmentId, replycallback);
      }
    });
  };

  exports.getAllUsers = function(callback) {
    var client;
    client = redis.createClient();
    return client.hgetall("users", function(err, reply) {
      client.quit();
      return callback(new Response(1, "success", reply));
    });
  };

}).call(this);
