// Generated by CoffeeScript 1.6.1
(function() {
  var Response, redis;

  redis = require("redis");

  Response = require('../vo/response').Response;

  exports.createUser = function(userName, password, departmentId, superiorId, callback) {
    var client;
    client = redis.createClient();
    return client.incr("next_user_id", function(err, reply) {
      var replycallback, userId;
      userId = "" + reply;
      replycallback = function(err, reply) {
        var data;
        client.quit();
        if (superiorId) {
          data = {
            id: userId,
            userName: userName,
            departmentId: departmentId,
            superiorId: superiorId
          };
        } else {
          data = {
            id: userId,
            userName: userName,
            departmentId: departmentId
          };
        }
        return callback(new Response(1, 'success', data));
      };
      if (superiorId) {
        return client.hmset("users", "" + reply + ":user_name", userName, "" + reply + ":password", password, "" + reply + ":department_id", departmentId, "" + reply + ":superior_id", superiorId, replycallback);
      } else {
        return client.hmset("users", "" + reply + ":user_name", userName, "" + reply + ":password", password, "" + reply + ":department_id", departmentId, replycallback);
      }
    });
  };

  exports.getAllUsers = function(callback) {
    var client;
    client = redis.createClient();
    return client.hgetall("users", function(err, reply) {
      client.quit();
      return callback(new Response(1, "success", reply));
    });
  };

  exports.removeUser = function(userId, callback) {
    var client;
    client = redis.createClient();
    return client.hdel("users", "" + userId + ":user_name", "" + userId + ":password", "" + userId + ":department_id", "" + userId + ":superior_id", function(err, reply) {
      return client.hgetall("users", function(err, reply) {
        var childOfKey, key, newUsers, value;
        newUsers = {};
        for (key in reply) {
          value = reply[key];
          childOfKey = key.split(":");
          if (childOfKey[1] === "superior_id" && value === userId) {
            client.hdel("users", key);
          } else {
            newUsers[key] = value;
          }
        }
        client.quit();
        return callback(new Response(1, "success", newUsers));
      });
    });
  };

}).call(this);
